version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of company
        columns:
          - name: date_date
            description: date of teh sales
          - name: orders_id
            description: identy the order
          - name: pdt_id
            description: product id
          - name: revenue
            description: revenue made
          - name: quantity
            description: qty purchased
      - name: product
        identifier: raw_gz_product
        description: products sold by company
        columns:
          - name: products_id
            description: unique ident of products
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship cost for each order
        columns:
          - name: orders_id
            description: unique ident of ship
            tests:
              - unique
              - not_null
